import Head from "next/head";

import MainLayout from "@/layouts/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>D&D Starter Guide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout></MainLayout>
    </>
  );
}
