import Head from "next/head";
import {
  Box,
  Grid,
  GridItem,
  Heading,
  Icon,
  Kbd,
  Table,
  TableCaption,
  TableContainer,
  Tbody,
  Td,
  Text,
  Tfoot,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";

import Navbar from "@/components/navbar";

import { Body, Charisma, Soul } from "@/components/styled/charLimits";
import {
  GiD10,
  GiD12,
  GiD4,
  GiDiceTwentyFacesTwenty,
  GiDiceEightFacesEight,
  GiPerspectiveDiceSix,
} from "react-icons/gi";

export default function Home() {
  return (
    <>
      <Head>
        <title>D&D Starter Guide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box as="main"></Box>
    </>
  );
}
