import Head from "next/head";
import {
  Box,
  Grid,
  GridItem,
  Heading,
  Icon,
  Image,
  Text,
} from "@chakra-ui/react";

import Navbar from "@/components/navbar";

import { Body, Charisma, Soul } from "@/components/styled/charLimits";
import { GiBiceps, GiSheikahEye, GiDramaMasks } from "react-icons/gi";

const Stats = () => {
  return (
    <>
      <Head>
        <title>D&D Starter Guide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box as="main">
        <Heading as="h2" size="lg" pt={8} pb={4}>
          Character Resources
        </Heading>
        <Text>
          You may have heard about D&D characters having stats such as{" "}
          <strong>Strength</strong>, <strong>Dexterity</strong> and{" "}
          <strong>Wisdom</strong>.
        </Text>
        <Text>Well, guess what?</Text>
        <Image
          src="/we-dont-do-that-here.gif"
          alt="We don't do that here"
          height="180px"
          my={4}
        />

        <Text>
          Our version of D&D does not need to compensate for something and every
          character needs only three stats: <Body>Body</Body>, <Soul>Soul</Soul>{" "}
          and <Charisma>Charisma</Charisma>.
        </Text>

        <Grid templateColumns="repeat(3, 1fr)" my={6} w="50%">
          <GridItem>
            <Icon as={GiBiceps} w="100px" h="100px" color="palevioletred" />
            <Heading as="h4" size="sm">
              Body
            </Heading>
          </GridItem>
          <GridItem>
            <Icon
              as={GiSheikahEye}
              w="100px"
              h="100px"
              color="mediumslateblue"
            />
            <Heading as="h4" size="sm">
              Soul
            </Heading>
          </GridItem>
          <GridItem>
            <Icon as={GiDramaMasks} w="100px" h="100px" color="goldenrod" />
            <Heading as="h4" size="sm">
              Charisma
            </Heading>
          </GridItem>
        </Grid>

        <Text>
          It is also important not to think of these as some ultimate resources,
          or health points! These are mere limits that your character has at
          their disposition. Feel free to use them, you can replentish them
          later.
        </Text>
        <Text>
          If your character has for example 8 <Body>Body</Body> points and uses
          all of them, it does not mean they drop dead where they stand. It only
          means it has reached the limit of their bodily strength and will no
          longer be able to push their performances further.
        </Text>
        <Text>
          However, they will be still able to do anything they wish to do
          normally, as long as they roll successfully. They will be also able to
          avert bad outcomes, albeit for a certain price. More on managing
          resources in later paragraphs.
        </Text>
      </Box>
    </>
  );
};

export default Stats;
